export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_SERVICE = 'USER_SERVICE';

export const PROFILE_REPOSITORY = 'PROFILE_REPOSITORY';
export const PROFILE_SERVICE = 'PROFILE_SERVICE';

export const DATA_SOURCE = 'DATA_SOURCE';
