version: '3.9'
services:
  db:
    image: postgres:16
    container_name: family_todo_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: family-todo-app
    ports:
      - '5321:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
